import Head from 'next/head'
import { useRouter } from 'next/router'

import { Container } from './styles'
import { Header } from '@/components/Header'
import { ButtonRegister } from '@/components/ButtonRegister'

export default function Home() {
  const router = useRouter()


  function handleRegisterONG() {
    router.push('/RegisterONG')
  }

  function handleRegisterVoluntary() {
    router.push('/RegisterVoluntary')
  }

  return (
    <>
      <Head>
        <title>Seja Voluntário</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div>
          <Header
            title="ONG 🏩"
            description="Cadastre sua ONG e encontre voluntários para ajudar a transformar o mundo."
          />
          <ButtonRegister title="Cadastrar uma ONG" onClick={handleRegisterONG} />
        </div>
        <div>
          <Header
            title="Voluntário 👤"
            description="Encontre ONGs na sua cidade e ajude a transformar o mundo."
          />
          <ButtonRegister title="Sou Voluntário" onClick={handleRegisterVoluntary} />
        </div>
      </Container>
    </>
  )
}
