import Head from 'next/head'

import { Container } from './styles'
import { Header } from '@/components/Header'

export default function Home() {

  return (
    <>
      <Head>
        <title>Seja Voluntário</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Container>
        <h1>
          Juntos pela solidariedade: cadastre sua ONG ou seja um voluntário e ajude a fazer a diferença na vida de quem mais precisa!
        </h1>
      </Container>
    </>
  )
}
